server:
  port: 8080

spring:
  application:
    name: spring-ai-alibaba-deepresearch

  ai:
    openai:
      api-key: sk-3e2f44dfeae445e49ec5d81ff3a51ac4
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen-max
    tavily:
      api-key: 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
      max-results: 3
      include-raw-content: true
      include-images: true
      include-image-descriptions: true
    mcp:
      client:
        sse:
          servers-configuration: classpath:mcp-servers.json
        stdio:
          servers-configuration: classpath:mcp-servers.json
        toolcallback:
          enabled: true

logging:
  level:
    com.alibaba.cloud.ai.example.deepresearch: debug
